/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class gov_nysenate_ams_dao_AmsNativeDao */

#ifndef _Included_AmsNativeDao_Wrapper
#define _Included_AmsNativeDao_Wrapper
#ifdef __cplusplus
extern "C" {
#endif

/* JNI Type mappings */

#define STRING_TYPE "Ljava/lang/String;"
#define BOOLEAN_TYPE "Z"
#define BYTE_TYPE "B"
#define CHAR_TYPE "C"
#define SHORT_TYPE "S"
#define INT_TYPE "I"
#define LONG_TYPE "J"
#define FLOAT_TYPE "F"
#define DOUBLE_TYPE "D"
#define ARRAY_TYPE "["
#define NO_ARGS "()"

/* Method callers */

jobject getObjectFromMethod(JNIEnv * env, jclass cls, jobject instance, const char * methodName, const char * returnType);
jstring getStringFromMethod(JNIEnv * env, jclass cls, jobject instance, const char * methodName);
jboolean getBooleanFromMethod(JNIEnv * env, jclass cls, jobject instance, const char * methodName);
jint getIntFromMethod(JNIEnv * env, jclass cls, jobject instance, const char * methodName);

char * getC_String(JNIEnv * env, const jstring javaString);
void releaseC_String(JNIEnv * env, const char * cString, const jstring javaString);

void printJString(JNIEnv * env, const jstring string);

/*
 * Class:     gov_nysenate_ams_dao_AmsNativeDao
 * Method:    setupAmsLibrary
 * Signature: (Lgov/nysenate/ams/model/AmsSettings;)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_nysenate_ams_dao_AmsNativeDao_setupAmsLibrary
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gov_nysenate_ams_dao_AmsNativeDao
 * Method:    closeAmsLibrary
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_gov_nysenate_ams_dao_AmsNativeDao_closeAmsLibrary
  (JNIEnv *, jobject);

/*
 * Class:     gov_nysenate_ams_dao_AmsNativeDao
 * Method:    addressInquiry
 * Signature: (Lgov/nysenate/ams/model/Address;)Lgov/nysenate/ams/model/AddressInquiryResult;
 */
JNIEXPORT jobject JNICALL Java_gov_nysenate_ams_dao_AmsNativeDao_addressInquiry
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gov_nysenate_ams_dao_AmsNativeDao
 * Method:    cityStateLookup
 * Signature: (Ljava/lang/String;)Lgov/nysenate/ams/model/CityStateResult;
 */
JNIEXPORT jobject JNICALL Java_gov_nysenate_ams_dao_AmsNativeDao_cityStateLookup
  (JNIEnv *, jobject, jstring);

/*
 * Class:     gov_nysenate_ams_dao_AmsNativeDao
 * Method:    zip9Inquiry
 * Signature: (Ljava/lang/String;)Lgov/nysenate/ams/model/AddressInquiryResult;
 */
JNIEXPORT jobject JNICALL Java_gov_nysenate_ams_dao_AmsNativeDao_zip9Inquiry
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
